config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # The devise for below is added manually after installing devise for controllers
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # Defines the root path route ("/")
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes

  def update_posts_counter
    user.posts_counter = 0 if user.posts_counter.nil?
    user.increment!(:posts_counter)
  end

  def recent_five_comments
    comments.order!(created_at: :desc).limit(5)
  end

  # validations
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user.id).order(created_at: :desc)
  end

  def new
    @post = Post.new
    @user = User.find(params[:user_id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_post_path(current_user, @post)
      flash[:error] = 'Post successfuly created!'
    else
      flash[:error] = 'Error creating post'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: @post.id).includes(:user).order(created_at: :desc)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class="user-detail">
      <div class="image">
        <img class="user-image" src="<%= @user.photo %>" alt="user photo">
      </div>
      <div class="user-info">
        <h1 class="user-name"><%= @user.name %></h1>
        <h3 class="post-count">Number of posts: <%= @user.posts_counter %></h3>
      </div>
    </div>

    <div class="Delete">
        <% if can? :destroy, @post %>
         <%= button_to "Delete", @post %>
        <% end %>
    </div>

    <div class="add-new-form">
      <%= link_to "Add New Post", new_user_post_path, class: 'btn' %>
    </div>
    <div class="posts">
        <%@posts.each do |post|%>
            <%= render 'shared/post', post: post%>
        <%end%>
    </div>
    <div class="comments">
         <% @posts.includes(:user).each do |comment| %>
            <p><%= comment.user.name%> : <%= comment.text %> </p>
        <% end %>
    </div>
    <button type='submit'>Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>Create a Post </h1>

    <%= form_with model: [@user, @post] do |form| %>

        <div class="p-title" >
            <%= form.label :title %>
            <br>
            <%= form.text_field :title %>
        </div>

        <div class="p-text" >
            <%= form.label :text %>
            <br>
            <%= form.text_area :text %>
        </div>
        
        <div class="p-submit" >
            <%= form.submit "Add Post" %>
        </div>
  
    <% end %>

app/views/posts/show.html.erb
<div class="post-info">
    <div class="post-user-info">
      <p>Post : <%= @post.title %> by <%= @user.name %></p>
      <p>Comments: <%= @post.comments_counter%>, Likes: <%= @post.likes_counter%></p>
     <div class="add-comment">
        <a href="<%= params[:id] %>/comments/new">Add Comment</a>
      </div>
     <div class="like-button">
        <%= form_with url: user_post_likes_path(post_id: @post.id), method: :post do |form| %>
          <%= form.submit 'Like', class: 'btn' %>
        <% end %>
      </div>
    </div>
    <p><%= @post.text %></p>
    <div class="comments">
         <% @comments.includes(:user).each do |comment| %>
            <p><%= comment.user.name%> : <%= comment.text %> </p>
        <% end %>
    </div>
    <div class="Delete">
      <% if can? :destroy, comment %>
        <%= button_to "Delete", comment, user_post_comment_path(current_user,@post.id,comment),
     method: :delete%>
        <% end %>
    </div>
  </div>